// Generated by https://quicktype.io

export interface MovieDetails {
    id:          number;
    title:       string;
    posterUrl:   string;
    backdropUrl: string;
    rating:      null;
    overview:    string;
    tagline:     string;
    budget:      number;
    revenue:     number;
    imdbUrl:     string;
    tmdbUrl:     string;
    releaseDate: string;
    runTime:     number;
    price:       number;
    genres:      Genre[];
    trailers:    Trailer[];
    casts:       Cast[];
}

export interface Cast {
    id:          number;
    name:        string;
    profilePath: string;
    character:   string;
}

export interface Genre {
    id:   number;
    name: string;
}

export interface Trailer {
    id:         number;
    trailerUrl: string;
    name:       string;
}
